version: 2.1

jobs:
  run-test:
    executor: pw-jammy-development
    steps:
      - checkout
      - run: npm i -D @playwright/test
      - run: npx playwright install --with-deps chromium
      - run:
          name: Run test
          command: npx playwright test
      - store_test_results:
          path: ./
      - store_artifacts:
          path: ./test-results

workflows:
  run-test-workflow:
    jobs:
      - run-test

executors:
   pw-jammy-development:
     docker:
       - image: mcr.microsoft.com/playwright:v1.33.0-jammy